name: sample_login
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.0.3
  smooth_page_indicator: ^1.0.0+2
  flutter_otp_text_field: ^1.1.1
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.4
  flutter_screenutil: ^5.7.0
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.0.5
  otp_text_field: ^1.1.3

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21



flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/logos/
    - assets/images/onboarding/
    - assets/images/icons/
  uses-material-design: true

